// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createEventRaw = `-- name: CreateEventRaw :one
INSERT INTO events_raw (site_id, ts, visitor_id, session_id, name, pathname, referrer, utm_source, country, browser, os, device)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, site_id, ts, visitor_id, session_id, name, pathname, referrer, utm_source, country, browser, os, device
`

type CreateEventRawParams struct {
	SiteID    int64
	Ts        time.Time
	VisitorID []byte
	SessionID int64
	Name      string
	Pathname  string
	Referrer  sql.NullString
	UtmSource sql.NullString
	Country   sql.NullString
	Browser   sql.NullString
	Os        sql.NullString
	Device    sql.NullString
}

func (q *Queries) CreateEventRaw(ctx context.Context, arg CreateEventRawParams) (EventsRaw, error) {
	row := q.db.QueryRowContext(ctx, createEventRaw,
		arg.SiteID,
		arg.Ts,
		arg.VisitorID,
		arg.SessionID,
		arg.Name,
		arg.Pathname,
		arg.Referrer,
		arg.UtmSource,
		arg.Country,
		arg.Browser,
		arg.Os,
		arg.Device,
	)
	var i EventsRaw
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Ts,
		&i.VisitorID,
		&i.SessionID,
		&i.Name,
		&i.Pathname,
		&i.Referrer,
		&i.UtmSource,
		&i.Country,
		&i.Browser,
		&i.Os,
		&i.Device,
	)
	return i, err
}

const deleteEventRaw = `-- name: DeleteEventRaw :exec
DELETE FROM events_raw WHERE id = $1
`

func (q *Queries) DeleteEventRaw(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventRaw, id)
	return err
}

const getEventRawByID = `-- name: GetEventRawByID :one
SELECT id, site_id, ts, visitor_id, session_id, name, pathname, referrer, utm_source, country, browser, os, device FROM events_raw WHERE id = $1
`

func (q *Queries) GetEventRawByID(ctx context.Context, id int64) (EventsRaw, error) {
	row := q.db.QueryRowContext(ctx, getEventRawByID, id)
	var i EventsRaw
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Ts,
		&i.VisitorID,
		&i.SessionID,
		&i.Name,
		&i.Pathname,
		&i.Referrer,
		&i.UtmSource,
		&i.Country,
		&i.Browser,
		&i.Os,
		&i.Device,
	)
	return i, err
}

const listEventsRawBySiteID = `-- name: ListEventsRawBySiteID :many
SELECT id, site_id, ts, visitor_id, session_id, name, pathname, referrer, utm_source, country, browser, os, device FROM events_raw
WHERE site_id = $1
  AND ts >= $2
  AND ts < $3
ORDER BY ts DESC, id DESC
LIMIT $4
`

type ListEventsRawBySiteIDParams struct {
	SiteID int64
	Ts     time.Time
	Ts_2   time.Time
	Limit  int32
}

func (q *Queries) ListEventsRawBySiteID(ctx context.Context, arg ListEventsRawBySiteIDParams) ([]EventsRaw, error) {
	rows, err := q.db.QueryContext(ctx, listEventsRawBySiteID,
		arg.SiteID,
		arg.Ts,
		arg.Ts_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsRaw
	for rows.Next() {
		var i EventsRaw
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Ts,
			&i.VisitorID,
			&i.SessionID,
			&i.Name,
			&i.Pathname,
			&i.Referrer,
			&i.UtmSource,
			&i.Country,
			&i.Browser,
			&i.Os,
			&i.Device,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
