// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"time"
)

type EventsRaw struct {
	ID        int64
	SiteID    int64
	Ts        time.Time
	VisitorID []byte
	SessionID int64
	Name      string
	Pathname  string
	Referrer  sql.NullString
	UtmSource sql.NullString
	Country   sql.NullString
	Browser   sql.NullString
	Os        sql.NullString
	Device    sql.NullString
}

type Session struct {
	ID        int64
	UserID    int64
	TokenHash []byte
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Site struct {
	ID         int64
	UserID     int64
	Domain     string
	PublicSlug sql.NullString
	CreatedAt  time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
