// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package store

import (
	"context"
	"database/sql"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (user_id, domain, public_slug)
VALUES ($1, $2, $3)
RETURNING id, user_id, domain, public_slug, created_at
`

type CreateSiteParams struct {
	UserID     int64
	Domain     string
	PublicSlug sql.NullString
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, createSite, arg.UserID, arg.Domain, arg.PublicSlug)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Domain,
		&i.PublicSlug,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id=$1
`

func (q *Queries) DeleteSite(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSite, id)
	return err
}

const getSiteByDomain = `-- name: GetSiteByDomain :one
SELECT id, user_id, domain, public_slug, created_at FROM sites WHERE domain = $1
`

func (q *Queries) GetSiteByDomain(ctx context.Context, domain string) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSiteByDomain, domain)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Domain,
		&i.PublicSlug,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT id, user_id, domain, public_slug, created_at FROM sites WHERE id = $1
`

func (q *Queries) GetSiteByID(ctx context.Context, id int64) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSiteByID, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Domain,
		&i.PublicSlug,
		&i.CreatedAt,
	)
	return i, err
}

const listSitesByUserID = `-- name: ListSitesByUserID :many
SELECT id, user_id, domain, public_slug, created_at FROM sites WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListSitesByUserID(ctx context.Context, userID int64) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, listSitesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Domain,
			&i.PublicSlug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSite = `-- name: UpdateSite :one
UPDATE sites 
SET
    domain = COALESCE($1, domain),
    public_slug = COALESCE($2, public_slug)
WHERE id = $3
RETURNING id, user_id, domain, public_slug, created_at
`

type UpdateSiteParams struct {
	Domain     sql.NullString
	PublicSlug sql.NullString
	ID         int64
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, updateSite, arg.Domain, arg.PublicSlug, arg.ID)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Domain,
		&i.PublicSlug,
		&i.CreatedAt,
	)
	return i, err
}
