// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package store

import (
	"context"
	"time"
)

const statsBreakdownEvents = `-- name: StatsBreakdownEvents :many
SELECT
  name                                   AS value,
  count(*)::bigint                       AS pageviews,
  count(DISTINCT visitor_id)::bigint     AS visitors
FROM events_raw
WHERE site_id = $1
  AND ts >= $2
  AND ts <  $3
  AND name <> 'pageview'
GROUP BY name
ORDER BY pageviews DESC, value ASC
LIMIT $4
`

type StatsBreakdownEventsParams struct {
	SiteID   int64
	FromTs   time.Time
	ToTs     time.Time
	RowLimit int32
}

type StatsBreakdownEventsRow struct {
	Value     string
	Pageviews int64
	Visitors  int64
}

func (q *Queries) StatsBreakdownEvents(ctx context.Context, arg StatsBreakdownEventsParams) ([]StatsBreakdownEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, statsBreakdownEvents,
		arg.SiteID,
		arg.FromTs,
		arg.ToTs,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsBreakdownEventsRow
	for rows.Next() {
		var i StatsBreakdownEventsRow
		if err := rows.Scan(&i.Value, &i.Pageviews, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsBreakdownPages = `-- name: StatsBreakdownPages :many
SELECT
  pathname                               AS value,
  count(*)::bigint                       AS pageviews,
  count(DISTINCT visitor_id)::bigint     AS visitors
FROM events_raw
WHERE site_id = $1
  AND ts >= $2
  AND ts <  $3
  AND name = 'pageview'
GROUP BY pathname
ORDER BY pageviews DESC, value ASC
LIMIT $4
`

type StatsBreakdownPagesParams struct {
	SiteID   int64
	FromTs   time.Time
	ToTs     time.Time
	RowLimit int32
}

type StatsBreakdownPagesRow struct {
	Value     string
	Pageviews int64
	Visitors  int64
}

func (q *Queries) StatsBreakdownPages(ctx context.Context, arg StatsBreakdownPagesParams) ([]StatsBreakdownPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, statsBreakdownPages,
		arg.SiteID,
		arg.FromTs,
		arg.ToTs,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsBreakdownPagesRow
	for rows.Next() {
		var i StatsBreakdownPagesRow
		if err := rows.Scan(&i.Value, &i.Pageviews, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsBreakdownReferrers = `-- name: StatsBreakdownReferrers :many
SELECT
  coalesce(referrer, '')::text           AS value,
  count(*)::bigint                       AS pageviews,
  count(DISTINCT visitor_id)::bigint     AS visitors
FROM events_raw
WHERE site_id = $1
  AND ts >= $2
  AND ts <  $3
  AND name = 'pageview'
  AND referrer IS NOT NULL
GROUP BY referrer
ORDER BY pageviews DESC, value ASC
LIMIT $4
`

type StatsBreakdownReferrersParams struct {
	SiteID   int64
	FromTs   time.Time
	ToTs     time.Time
	RowLimit int32
}

type StatsBreakdownReferrersRow struct {
	Value     string
	Pageviews int64
	Visitors  int64
}

func (q *Queries) StatsBreakdownReferrers(ctx context.Context, arg StatsBreakdownReferrersParams) ([]StatsBreakdownReferrersRow, error) {
	rows, err := q.db.QueryContext(ctx, statsBreakdownReferrers,
		arg.SiteID,
		arg.FromTs,
		arg.ToTs,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsBreakdownReferrersRow
	for rows.Next() {
		var i StatsBreakdownReferrersRow
		if err := rows.Scan(&i.Value, &i.Pageviews, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsSummary = `-- name: StatsSummary :one
SELECT
  count(*)::bigint                       AS pageviews,
  count(DISTINCT visitor_id)::bigint     AS visitors
FROM events_raw
WHERE site_id = $1
  AND ts >= $2
  AND ts <  $3
  AND name = 'pageview'
`

type StatsSummaryParams struct {
	SiteID int64
	FromTs time.Time
	ToTs   time.Time
}

type StatsSummaryRow struct {
	Pageviews int64
	Visitors  int64
}

func (q *Queries) StatsSummary(ctx context.Context, arg StatsSummaryParams) (StatsSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, statsSummary, arg.SiteID, arg.FromTs, arg.ToTs)
	var i StatsSummaryRow
	err := row.Scan(&i.Pageviews, &i.Visitors)
	return i, err
}

const statsTimeseriesDaily = `-- name: StatsTimeseriesDaily :many
SELECT
  b.bucket::timestamptz                  AS bucket,
  count(e.id)::bigint                    AS pageviews,
  count(DISTINCT e.visitor_id)::bigint   AS visitors
FROM generate_series(
  date_trunc('day', $1::timestamptz),
  date_trunc('day', $2::timestamptz - interval '1 microsecond'),
  interval '1 day'
) AS b(bucket)
LEFT JOIN events_raw e
  ON e.site_id = $3
 AND e.name = 'pageview'
 AND e.ts >= b.bucket
 AND e.ts <  b.bucket + interval '1 day'
GROUP BY b.bucket
ORDER BY b.bucket
`

type StatsTimeseriesDailyParams struct {
	FromTs time.Time
	ToTs   time.Time
	SiteID int64
}

type StatsTimeseriesDailyRow struct {
	Bucket    time.Time
	Pageviews int64
	Visitors  int64
}

func (q *Queries) StatsTimeseriesDaily(ctx context.Context, arg StatsTimeseriesDailyParams) ([]StatsTimeseriesDailyRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTimeseriesDaily, arg.FromTs, arg.ToTs, arg.SiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTimeseriesDailyRow
	for rows.Next() {
		var i StatsTimeseriesDailyRow
		if err := rows.Scan(&i.Bucket, &i.Pageviews, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTimeseriesHourly = `-- name: StatsTimeseriesHourly :many
SELECT
  b.bucket::timestamptz                  AS bucket,
  count(e.id)::bigint                    AS pageviews,
  count(DISTINCT e.visitor_id)::bigint   AS visitors
FROM generate_series(
  date_trunc('hour', $1::timestamptz),
  date_trunc('hour', $2::timestamptz - interval '1 microsecond'),
  interval '1 hour'
) AS b(bucket)
LEFT JOIN events_raw e
  ON e.site_id = $3
 AND e.name = 'pageview'
 AND e.ts >= b.bucket
 AND e.ts <  b.bucket + interval '1 hour'
GROUP BY b.bucket
ORDER BY b.bucket
`

type StatsTimeseriesHourlyParams struct {
	FromTs time.Time
	ToTs   time.Time
	SiteID int64
}

type StatsTimeseriesHourlyRow struct {
	Bucket    time.Time
	Pageviews int64
	Visitors  int64
}

func (q *Queries) StatsTimeseriesHourly(ctx context.Context, arg StatsTimeseriesHourlyParams) ([]StatsTimeseriesHourlyRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTimeseriesHourly, arg.FromTs, arg.ToTs, arg.SiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTimeseriesHourlyRow
	for rows.Next() {
		var i StatsTimeseriesHourlyRow
		if err := rows.Scan(&i.Bucket, &i.Pageviews, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
